apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER_NAME
spec:
  template:
    spec:
      containers:
      - name: PLACEHOLDER_NAME-container
        image: PLACEHOLDER_IMAGE
        env: 
          - name: PRODUCER_TOPIC
            value: "PLACEHOLDER_PRODUCER_TOPIC"
          - name: CONSUMER_TOPIC
            value: "PLACEHOLDER_CONSUMER_TOPIC"
      restartPolicy: Never
