
    FROM python:3.12
    WORKDIR /app
    COPY cell4.py /app
    COPY ResultsHub.py /app
    COPY J2kResultsHub_pb2.py /app
    COPY J2kResultsHub_pb2_grpc.py /app
    COPY requirements.txt /app
    RUN pip install --ignore-installed -r requirements.txt  # Add the --ignore-installed flag
    CMD ["python", "/app/cell4.py"]
    