
    FROM python:3.11
    WORKDIR /app
    COPY cell_4.py /app
    COPY requirements.txt /app
    RUN pip install --ignore-installed -r requirements.txt  # Add the --ignore-installed flag
    CMD ["python", "/app/cell_4.py"]
    